"""
Django settings for TheSuite (HR & Payroll SaaS) project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================
# SECURITY SETTINGS
# ============================

SECRET_KEY = "django-insecure-rgikx&$w(5exao@fu4ui1p-kgx^))3w0u(5i98n=-4_7kke50+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed hosts - Be more restrictive in production
ALLOWED_HOSTS = ["*"]   # Change to specific domains in production (e.g., ['api.thesuite.com'])

# ============================
# APPLICATION DEFINITION
# ============================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_filters',          # Good to have for filtering in payroll/employees

    # Local apps
    'accounts',
    'companies',
    'employees',
    'attendance',
    'leave',
    'payroll',
    'subscriptions',
    'notifications',
    'ai_init',
    'appsettings',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',   # Must be at the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "config.urls"

# ============================
# TEMPLATES (For Email Only)
# ============================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],      # Global templates folder (optional)
        "APP_DIRS": True,                      # Important: allows templates inside apps/accounts/templates/
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ============================
# DATABASE
# ============================


if DEBUG:
    print("DEBUG MODE")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    print("PRODUCTION MODE")
    DB_PASSWORD = "F2VytBR3UIgJuvo8"
    
    import dj_database_url
    import os
    
    DATABASES = {
        'default': dj_database_url.config(
            default=f"postgresql://postgres.ljsoxykpwcejcdrsjkzw:{DB_PASSWORD}@aws-0-eu-west-1.pooler.supabase.com:6543/postgres"
        )
    }

# ============================
# AUTHENTICATION & USERS
# ============================

AUTH_USER_MODEL = 'accounts.User'

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ============================
# INTERNATIONALIZATION & TIME
# ============================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Lagos"      # Correct for Lagos, Nigeria
USE_I18N = True
USE_TZ = True

# ============================
# STATIC FILES
# ============================

STATIC_URL = "static/"

# ============================
# REST FRAMEWORK SETTINGS
# ============================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Optional: Better error messages for API
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
}

# ============================
# CORS SETTINGS (Improved for React)
# ============================
FRONTEND_URL = "http://51.20.54.232:8000"

# "https://thesuit.netlify.app"

# "https://thesuit.onrender.com"

# "https://hr-suit-connect.vercel.app"
#"https://thesuit.netlify.app"

# Better than CORS_ALLOW_ALL_ORIGINS=True (more secure)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",           # React dev server
    "http://127.0.0.1:3000",
    FRONTEND_URL, 
    "https://walex-projects.github.io",
    "http://13.61.24.57:8080",  # Your production frontend
    # Add more frontend URLs later (e.g., Vercel, custom domain)
    "http://localhost:2435",
]

# Allow credentials (important if you send cookies or Authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allow specific headers and methods (recommended)
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ============================
# EMAIL SETTINGS (Gmail)
# ============================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'bestigbekele5@gmail.com'
EMAIL_HOST_PASSWORD = 'odsp jybe ptfe emdq'

DEFAULT_FROM_EMAIL = "TheSuite <noreply@Thesuite.com>"   # More professional

# ============================
# PAYSTACK (Payment Gateway)
# ============================

PAYSTACK_SECRET_KEY = "sk_test_1227fdebab940274c36e42da3b78d7d8b8ae9ca7"

# ============================
# OTHER USEFUL SETTINGS
# ============================

# SimpleJWT settings (recommended defaults)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}










"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-rgikx&$w(5exao@fu4ui1p-kgx^))3w0u(5i98n=-4_7kke50+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

PAYSTACK_SECRET_KEY="sk_test_1227fdebab940274c36e42da3b78d7d8b8ae9ca7"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # Local apps
    'accounts',
    'companies',
    'employees',
    'attendance',
    'leave',
    'payroll',
    'subscriptions',
    'notifications',
    'ai_init',
    "appsettings"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],   # Optional global templates folder
        'APP_DIRS': True,               
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

#TIME_ZONE = "UTC"

USE_I18N = True

#USE_TZ = True

TIME_ZONE = "Africa/Lagos"
USE_TZ = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}
# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'bestigbekele5@gmail.com'
EMAIL_HOST_PASSWORD = 'odsp jybe ptfe emdq'



DEFAULT_FROM_EMAIL = "noreply@Thesuite.com"
"""