# Generated by Django 6.0.3 on 2026-05-07 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_hours_per_day", models.PositiveIntegerField(default=8)),
                ("allow_late_arrival", models.BooleanField(default=True)),
                ("late_arrival_grace_minutes", models.PositiveIntegerField(default=15)),
                ("require_face_verification", models.BooleanField(default=False)),
                ("geo_fencing_enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_settings",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
