# Generated by Django 6.0.3 on 2026-05-07 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_attendancesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_annual_leave_days", models.PositiveIntegerField(default=21)),
                ("default_sick_leave_days", models.PositiveIntegerField(default=10)),
                ("carry_forward_enabled", models.BooleanField(default=True)),
                ("max_carry_forward_days", models.PositiveIntegerField(default=10)),
                ("leave_approval_required", models.BooleanField(default=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_settings",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payroll_day", models.PositiveIntegerField(default=25)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=7.5, max_digits=5),
                ),
                ("allow_manual_payslip", models.BooleanField(default=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_settings",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications_enabled", models.BooleanField(default=True)),
                ("allow_self_registration", models.BooleanField(default=False)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("session_timeout_minutes", models.PositiveIntegerField(default=60)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_settings",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Head Office", max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("radius_meters", models.PositiveIntegerField(default=100)),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_location",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
