# Generated by Django 6.0.3 on 2026-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_leavesettings_payrollsettings_systemsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_id",
            field=models.CharField(
                default="AutoSheck-0001", editable=False, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
