# Generated by Django 6.0.3 on 2026-05-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesettings",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancesettings",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
