# Generated by Django 6.0.3 on 2026-05-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("subscriptions", "0002_coupon_remove_subscription_next_billing_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="companies.company",
            ),
        ),
    ]
