# Generated by Django 6.0.3 on 2026-05-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscription_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="price",
            new_name="base_price",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="trial_days",
        ),
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="price_per_employee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug",
            field=models.SlugField(default="starter", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="has_attendance",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="has_leave",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="max_employees",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
