# Generated by Django 6.0.3 on 2026-05-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_rename_price_plan_base_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="duration_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="trial_days",
            field=models.IntegerField(default=0),
        ),
    ]
